# Generated by Django 3.0.8 on 2020-07-11 15:56

import api.apps.server_manager.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'BIND': {'kek': 'lol'}, 'POSTFIX': {'ip': '127.0.0.1', 'port': '52'}}, validators=[api.apps.server_manager.validators.validate_json_settings]),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_name',
            field=models.CharField(default='O4WICLms', max_length=16),
        ),
        migrations.AlterModelTable(
            name='server',
            table='servers',
        ),
        migrations.AlterModelTable(
            name='serverconnection',
            table='server_connections',
        ),
    ]
