# Generated by Django 3.0.8 on 2020-07-27 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_name',
            field=models.CharField(default='D1hLeRZ3', max_length=16, verbose_name='Server name to show in client'),
        ),
        migrations.AlterField(
            model_name='simplesshconnector',
            name='server_ref',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='server_manager.Server', verbose_name='Server ref'),
        ),
        migrations.AlterModelTable(
            name='connectortype',
            table='connector_types',
        ),
    ]
