# Generated by Django 3.0.8 on 2020-07-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverconfig',
            name='server_name',
            field=models.CharField(default='DZeB0', max_length=16, verbose_name='Server name to show in client'),
        ),
    ]
