# Generated by Django 3.0.8 on 2020-07-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0002_auto_20200729_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverconfig',
            old_name='modified',
            new_name='modificated',
        ),
        migrations.AlterField(
            model_name='serverconfig',
            name='server_name',
            field=models.CharField(default='hebWY', max_length=16, verbose_name='Server name to show in client'),
        ),
    ]
