# Generated by Django 3.0.8 on 2020-07-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0002_auto_20200711_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_name',
            field=models.CharField(default='sNGTrTUO', max_length=16),
        ),
    ]
