# Generated by Django 3.0.8 on 2020-07-13 07:35

import api.apps.core.stage
import api.apps.server_manager.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0003_auto_20200711_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='server',
            name='status',
        ),
        migrations.RemoveField(
            model_name='serverconnection',
            name='server',
        ),
        migrations.AddField(
            model_name='server',
            name='server_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=api.apps.core.stage.get_default_server_settings, validators=[api.apps.server_manager.validators.validate_json_settings], verbose_name='JSON with settings for             SMTP(POSTFIX) and DNS(BIND) services'),
        ),
        migrations.AddField(
            model_name='serverconnection',
            name='server_ref',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='server_manager.Server', verbose_name='SSH. Password for connection to server'),
        ),
        migrations.AlterField(
            model_name='server',
            name='is_connected',
            field=models.BooleanField(default=False, verbose_name='Flag to show active servers'),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_ip',
            field=models.GenericIPAddressField(verbose_name='Server ip to connections'),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_name',
            field=models.CharField(default='NGf8ZB4D', max_length=16, verbose_name='Server name to show in client'),
        ),
        migrations.AlterField(
            model_name='serverconnection',
            name='ssh_password',
            field=models.CharField(max_length=256, verbose_name='SSH. Password for connection to server'),
        ),
        migrations.AlterField(
            model_name='serverconnection',
            name='ssh_username',
            field=models.CharField(max_length=64, verbose_name='SSH. Username for connection to server'),
        ),
    ]
