# Generated by Django 3.0.8 on 2020-07-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0004_auto_20200713_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_name',
            field=models.CharField(default='Y0gpCDrw', max_length=16, verbose_name='Server name to show in client'),
        ),
    ]
